// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScanResults(arg1) {
  return window['go']['main']['App']['AddScanResults'](arg1);
}

export function AutoClassify() {
  return window['go']['main']['App']['AutoClassify']();
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteShortcut(arg1) {
  return window['go']['main']['App']['DeleteShortcut'](arg1);
}

export function GetCategories(arg1) {
  return window['go']['main']['App']['GetCategories'](arg1);
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function LaunchShortcut(arg1) {
  return window['go']['main']['App']['LaunchShortcut'](arg1);
}

export function ListShortcuts(arg1) {
  return window['go']['main']['App']['ListShortcuts'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function RenameCategory(arg1, arg2) {
  return window['go']['main']['App']['RenameCategory'](arg1, arg2);
}

export function ScanPrograms(arg1) {
  return window['go']['main']['App']['ScanPrograms'](arg1);
}

export function UpdateShortcutCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateShortcutCategory'](arg1, arg2);
}
