// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddScanResults(arg1:Array<main.ScanResult>):Promise<number>;

export function AutoClassify():Promise<number>;

export function CreateCategory(arg1:string):Promise<string>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteShortcut(arg1:number):Promise<void>;

export function GetCategories(arg1:boolean):Promise<Array<string>>;

export function GetOverview():Promise<main.Overview>;

export function LaunchShortcut(arg1:number):Promise<void>;

export function ListShortcuts(arg1:main.ShortcutFilter):Promise<Array<main.Shortcut>>;

export function OpenFileLocation(arg1:number):Promise<void>;

export function RenameCategory(arg1:string,arg2:string):Promise<void>;

export function ScanPrograms(arg1:main.ScanOptions):Promise<Array<main.ScanResult>>;

export function UpdateShortcutCategory(arg1:number,arg2:string):Promise<void>;
